<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateUserRolesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('user_roles', function (Blueprint $table) {
            $table->id();
            $table->string('Role_name');
            $table->string('description')->nullable();
            $table->boolean('addUser')->default(0);
            $table->boolean('viewUser')->default(0);
            $table->boolean('updateUser')->default(0);
            $table->boolean('deleteUser')->default(0);
            $table->boolean('inactivateUser')->default(0);
            $table->boolean('addUserRole')->default(0);
            $table->boolean('viewUserRole')->default(0);
            $table->boolean('updateUserRole')->default(0);
            $table->boolean('deleteUserRole')->default(0);
            $table->boolean('addProduct')->default(0);
            $table->boolean('viewProduct')->default(0);
            $table->boolean('updateProduct')->default(0);
            $table->boolean('deleteProduct')->default(0);
            $table->boolean('showCostPrice')->default(0);
            $table->boolean('editQuantity')->default(0);
            $table->boolean('editPrice')->default(0);
            $table->boolean('printbarcodes')->default(0);
            $table->boolean('exportProducts')->default(0);
            $table->boolean('addStaff')->default(0);
            $table->boolean('viewStaff')->default(0);
            $table->boolean('updateStaff')->default(0);
            $table->boolean('deleteStaff')->default(0);
            $table->boolean('edit_staff_attendance')->default(0);
            $table->boolean('mark_staff_attendance')->default(0);
            $table->boolean('exportStaff')->default(0);
            $table->boolean('addCustomer')->default(0);
            $table->boolean('viewCustomer')->default(0);
            $table->boolean('updateCustomer')->default(0);
            $table->boolean('deleteCustomer')->default(0);
            $table->boolean('editLoyaltyPoints')->default(0);
            $table->boolean('exportCustomers')->default(0);
            $table->boolean('addVendor')->default(0);
            $table->boolean('viewVendor')->default(0);
            $table->boolean('updateVendor')->default(0);
            $table->boolean('deleteVendor')->default(0);
            $table->boolean('exportVendors')->default(0);
            $table->boolean('addInventory')->default(0);
            $table->boolean('viewInventory')->default(0);
            $table->boolean('updateInventory')->default(0);
            $table->boolean('deleteInventory')->default(0);
            $table->boolean('exportInventories')->default(0);
            $table->boolean('newInventoryCount')->default(0);
            $table->boolean('editInventoryCount')->default(0);
            $table->boolean('viewInventoryCount')->default(0);
            $table->boolean('printInventoryCount')->default(0);
            $table->boolean('setInventoryCountCompleted')->default(0);
            $table->boolean('deleteInventoryCount')->default(0);
            $table->boolean('inventoryTransfer')->default(0);
            $table->boolean('editInventoryTransfer')->default(0);
            $table->boolean('deleteInventoryTransfer')->default(0);
            $table->boolean('addExpense')->default(0);
            $table->boolean('viewExpense')->default(0);
            $table->boolean('updateExpense')->default(0);
            $table->boolean('deleteExpense')->default(0);
            $table->boolean('addVoucher')->default(0);
            $table->boolean('viewVoucher')->default(0);
            $table->boolean('updateVoucher')->default(0);
            $table->boolean('deleteVoucher')->default(0);
            $table->boolean('exportVoucher')->default(0);
            $table->boolean('addLoyalty')->default(0);
            $table->boolean('viewLoyalty')->default(0);
            $table->boolean('updateLoyalty')->default(0);
            $table->boolean('deleteLoyalty')->default(0);
            $table->boolean('exportLoyalty')->default(0);
            $table->boolean('createPurchaseOrder')->default(0);
            $table->boolean('viewPurchaseOrder')->default(0);
            $table->boolean('updatePurchaseOrder')->default(0);
            $table->boolean('deletePurchaseOrder')->default(0);
            $table->boolean('printPurchaseInvoice')->default(0);
            $table->boolean('exportPurchaseOrder')->default(0);
            $table->boolean('generateGRN')->default(0);
            $table->boolean('makeSalaryPayment')->default(0);
            $table->boolean('viewSalaryPayment')->default(0);
            $table->boolean('updateSalaryPayment')->default(0);
            $table->boolean('deleteSalaryPayment')->default(0);
            $table->boolean('printSalaryPaymentInvoice')->default(0);
            $table->boolean('makeVendorPayment')->default(0);
            $table->boolean('viewVendorPayment')->default(0);
            $table->boolean('updateVendorPayment')->default(0);
            $table->boolean('deleteVendorPayment')->default(0);
            $table->boolean('printVendorPaymentInvoice')->default(0);
            $table->boolean('processSale')->default(0);
            $table->boolean('accessBackend')->default(0);
            $table->boolean('openRegister')->default(0);
            $table->boolean('closeRegister')->default(0);
            $table->boolean('retrieveSale')->default(0);
            $table->boolean('parkSale')->default(0);
            $table->boolean('suspendSale')->default(0);
            $table->boolean('giveDiscount')->default(0);
            $table->boolean('printDayEndReport')->default(0);
            $table->boolean('viewSale')->default(0);
            $table->boolean('updateSale')->default(0);
            $table->boolean('deleteSale')->default(0);
            $table->boolean('viewProfit')->default(0);
            $table->boolean('deleteSuspendedSales')->default(0);
            $table->boolean('addbankAccounts')->default(0);
            $table->boolean('viewbankAccounts')->default(0);
            $table->boolean('updatebankAccounts')->default(0);
            $table->boolean('deletebankAccounts')->default(0);
            $table->boolean('createPromotions')->default(0);
            $table->boolean('viewPromotions')->default(0);
            $table->boolean('updatePromotions')->default(0);
            $table->boolean('deletePromotions')->default(0);
            $table->boolean('removeProductsFromPromotion')->default(0);
            $table->boolean('viewPromotionSummary')->default(0);
            $table->boolean('printPromotionSummaryReport')->default(0);
            $table->boolean('addService')->default(0);
            $table->boolean('viewService')->default(0);
            $table->boolean('updateService')->default(0);
            $table->boolean('deleteService')->default(0);
            $table->boolean('exchangeProducts')->default(0);
            $table->boolean('viewExchange')->default(0);
            $table->boolean('updateExchange')->default(0);
            $table->boolean('deleteExchange')->default(0);
            $table->boolean('productReport')->default(0);
            $table->boolean('categoriesReport')->default(0);
            $table->boolean('employeeReport')->default(0);
            $table->boolean('attendanceReport')->default(0);
            $table->boolean('bankAccountReport')->default(0);
            $table->boolean('salaryReport')->default(0);
            $table->boolean('commissionReport')->default(0);
            $table->boolean('customersReport')->default(0);
            $table->boolean('salesReport')->default(0);
            $table->boolean('balanceChart')->default(0);
            $table->boolean('expensesReport')->default(0);
            $table->boolean('voucherReport')->default(0);
            $table->boolean('inventoryReport')->default(0);
            $table->boolean('loyaltyReport')->default(0);
            $table->boolean('profitReport')->default(0);
            $table->boolean('paymentReport')->default(0);
            $table->boolean('purchasesReport')->default(0);
            $table->boolean('vendorsReport')->default(0);
            $table->boolean('serviceReport')->default(0);
            $table->boolean('stockTransferReport')->default(0);
            $table->boolean('viewDashboardStatistics')->default(0);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('user-roles');
    }
}
